// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Container: typeof import('./components/Container.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    GlobalCom: typeof import('./componentsGlobal/globalCom.vue')['default']
    LeftSidebar: typeof import('./components/container/leftSidebar.vue')['default']
    MouseSelect: typeof import('./components/mouseSelect.vue')['default']
    TestGlobalCom: typeof import('./componentsGlobal/test/testGlobalCom.vue')['default']
    TopNavBar: typeof import('./components/container/topNavBar.vue')['default']
  }
}

export { }
